import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { rightGroteskTight } from "./fonts";
import SplashLoaderCurtain from "@/components/SplashLoader";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Victor Alvarez",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className="scroll-smooth">
      <body className={`${inter.variable} ${rightGroteskTight.variable} bg-white text-black antialiased`}>
        <SplashLoaderCurtain />
        {children}
      </body>
    </html>
  );
}